import Navbar from './components/navbar'
import './globals.css'

export const metadata = {
  title: 'Equality Mastermind',
  description: 'Generated by create next app and proexidno',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className='sm:text-lg md:text-xl font-bold lg:text-2xl xl:text-3xl'>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
